### ISSUE TITLE
Error with undetected_chromedrivert

### ISSUE THREAD

**Issue by mandy132** [tp223/Driving-Test-Cancellations#8]
I am getting the following error when trying to run this 

```
Traceback (most recent call last):
  File "/Users/andrewphillips/Documents/GitHub/Driving-Test-Cancellations/main.py", line 9, in <module>
    uc.install()
AttributeError: module 'undetected_chromedriver' has no attribute 'install'
```

I was wondering if you had any ideas as to what I'm doing wrong

thank you!

**Comment by konrad-wila** [comment]
You can to roll back to an older (v1 methods) version of the undetected-chromedriver PIP package since the newer versions use a different v2 methods system to fix the issue. Although this will likely lead to the bot being detected on the DVLA website.

[https://github.com/ultrafunkamsterdam/undetected-chromedriver](url)

P.S. I think this project has been abandoned, when you go to [copadrivingtest.co.uk](url) you can't even pay to have the project hosted online.
